sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install 'coverage<4'
  - pip install coveralls
script:
  - coverage run --source=tryagain -m py.test
after_success:
  - coveralls
